services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    build: .
    container_name: auth-service
    restart: always
    ports:
      - "8130:8130"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpass

volumes:
  mysql_data: